const API_PREFIX = "/api";
const CURRENT_API_VERSION = "1";
const REST_INTERFACE_PREFIX = `${API_PREFIX}/${CURRENT_API_VERSION}`;

export {
    API_PREFIX,
    CURRENT_API_VERSION,
    REST_INTERFACE_PREFIX
};
